name: "Test Release Actions"
on:
  release:
    types:
      - created
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Output"
        run: git describe --tags
      - name: "Output 2"
        run: echo ${{ github.event.release.draft }}
