name: "Test Release Actions"
on:
  release:
    types:
      - published
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v2
      - name: "Output"
        run: echo "RELEASE_VERSION=$(${{ github.event.release.tag_name }} | cut -c 2- )" >> $GITHUB_ENV
      - name: "Output 2"
        run: echo ${{ env.RELEASE_VERSION }}
      - name: "is a pre release check"
        run: echo ${{ github.event.release.prerelease }}
      - name: "edited release check"
        run: echo ${{ github.event.release.tag_name }}
