# This is a basic workflow to help you get started with Actions

name: PR CLOSED

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    types: [closed]
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: "Dump Github Context"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: "Remove Previous Docker Image"
        run: |
            if [ -z ${{ github.event.pull_request.merge_commit_sha }} ]; then
              echo "First commit, no previous image to remove"
            else
              echo ${{ github.event.pull_request.merge_commit_sha }}
            fi
