name: "Testing Hash"
on:
  push:
    branches:
      - master
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: Dev
      url: https://google.com

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      - name: "See Current Hash"
        run: |
            echo ${{ github.event.pull_request.head.sha }}
            echo ${{ github.sha }}
      - name: "Show Github Context"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
